export default {
	GET_POSTS: 'GET_POSTS',
	POSTS_ERROR: 'POSTS_ERROR',
	UPDATE_LIKES: 'UPDATE_LIKES',
  DELETE_POST: 'DELETE_POST',
	ADD_POST: "ADD_POST",
	GET_POST: "GET_POST",
	POST_ERROR: "POST_ERROR",
	ADD_COMMENT: "ADD_COMMENT",
	COMMENT_ERROR: "COMMENT_ERROR",
	DELETE_COMMENT: "DELETE_COMMENT"
};
