const ProfileActionTypes = {
  GET_PROFILE: "GET_PROFILE",
  PROFILE_ERROR: "PROFILE_ERROR",
  CLEAR_PROFILE: "CLEAR_PROFILE",
  CREATE_PROFILE: "CREATE_PROFILE",
  CREATE_ERROR: "CREATE_ERROR"
};

export default ProfileActionTypes;