const ProfileActionTypes = {
  GET_PROFILE: "GET_PROFILE",
  PROFILE_ERROR: "PROFILE_ERROR",
  CLEAR_PROFILE: "CLEAR_PROFILE",
  CREATE_PROFILE: "CREATE_PROFILE",
  CREATE_ERROR: "CREATE_ERROR",
  ADD_EXPERIENCE: "ADD_EXPERIENCE",
  ADD_EDUCATION: "ADD_EDUCATION",
  GET_ALL_PROFILES: "GET_ALL_PROFILES",
  PROFILES_ERROR: "PROFILES_ERROR",
};

export default ProfileActionTypes;